import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { WeekNavigator } from "@/components/planning-ui";
import { formatHours, summarizeWeeklyHours } from "@/lib/planning-utils";
import { usePlanning } from "@/providers/planning-provider";
import { useRouter } from "expo-router";
import { FlatList, Pressable, Text, View } from "react-native";

export default function DashboardScreen() {
  const router = useRouter();
  const { isAdmin, snapshot } = usePlanning();
  if (!isAdmin) return <ScreenContainer className="items-center justify-center px-8"><IconSymbol name="lock.fill" size={34} color="#60788A" /><Text className="mt-4 text-xl font-bold text-foreground">Accès administrateur requis</Text><Text className="mt-2 text-center text-muted">Le récapitulatif des heures est réservé à la gestion de l’équipe.</Text></ScreenContainer>;
  const rows = summarizeWeeklyHours(snapshot.members, snapshot.shifts);
  const totalMinutes = rows.reduce((total, row) => total + row.minutes, 0);
  const maxMinutes = Math.max(...rows.map((row) => row.minutes), 1);
  const highest = rows[0];
  return <ScreenContainer><FlatList data={rows} keyExtractor={(row) => String(row.member.id)} contentContainerStyle={{ padding: 20, paddingBottom: 32, gap: 12 }} ListHeaderComponent={<View className="gap-5 mb-2"><View className="flex-row items-center justify-between"><Pressable onPress={() => router.back()} style={({ pressed }) => ({ opacity: pressed ? 0.6 : 1 })}><Text className="text-base font-bold text-primary">Retour</Text></Pressable><View className="rounded-full bg-[#E4F1FB] px-3 py-1.5"><Text className="text-xs font-bold text-foreground">Administration</Text></View></View><View><Text className="text-sm font-semibold uppercase tracking-widest text-primary">Suivi d’activité</Text><Text className="mt-1 text-3xl font-bold text-foreground">Heures de l’équipe</Text><Text className="mt-1 text-base text-muted">Total planifié pour chaque salarié sur la semaine.</Text></View><WeekNavigator /><View className="flex-row gap-3"><MetricCard label="Heures planifiées" value={formatHours(totalMinutes)} icon="clock.fill" /><MetricCard label="Salariés" value={String(rows.length)} icon="person.2.fill" /></View>{highest && <View className="rounded-3xl bg-foreground p-5"><Text className="text-sm font-semibold text-white/70">Volume le plus élevé</Text><Text className="mt-2 text-2xl font-bold text-white">{highest.member.name}</Text><Text className="mt-1 text-sm text-white/70">{formatHours(highest.minutes)} planifiées sur {highest.shiftCount} service{highest.shiftCount > 1 ? "s" : ""}</Text></View>}<Text className="mt-1 text-lg font-bold text-foreground">Détail par salarié</Text></View>} renderItem={({ item }) => <HoursRow row={item} maxMinutes={maxMinutes} />} ListEmptyComponent={<View className="rounded-3xl bg-surface border border-border p-6 items-center"><IconSymbol name="clock.fill" size={30} color="#60788A" /><Text className="mt-3 text-center font-semibold text-foreground">Aucune heure à récapituler</Text><Text className="mt-1 text-center text-sm text-muted">Ajoutez des services et affectez des salariés pour obtenir le suivi hebdomadaire.</Text></View>} /></ScreenContainer>;
}

function MetricCard({ label, value, icon }: { label: string; value: string; icon: "clock.fill" | "person.2.fill" }) { return <View className="flex-1 rounded-3xl bg-surface border border-border px-4 py-4"><IconSymbol name={icon} size={20} color="#E31837" /><Text className="mt-3 text-xl font-bold text-foreground">{value}</Text><Text className="mt-1 text-xs text-muted">{label}</Text></View>; }

function HoursRow({ row, maxMinutes }: { row: ReturnType<typeof summarizeWeeklyHours>[number]; maxMinutes: number }) { const width = Math.max(4, Math.round(row.minutes / maxMinutes * 100)); return <View className="rounded-3xl bg-surface border border-border p-4"><View className="flex-row items-center gap-3"><View style={{ backgroundColor: row.member.color }} className="h-11 w-11 rounded-2xl items-center justify-center"><Text className="text-xs font-bold text-white">{row.member.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</Text></View><View className="flex-1"><Text className="text-base font-bold text-foreground">{row.member.name}</Text><Text className="mt-1 text-sm text-muted">{row.member.jobTitle} · {row.shiftCount} service{row.shiftCount > 1 ? "s" : ""}</Text></View><Text className="text-base font-bold text-primary">{formatHours(row.minutes)}</Text></View><View className="mt-4 h-2 overflow-hidden rounded-full bg-[#EAF0F4]"><View style={{ width: `${width}%`, backgroundColor: row.member.color }} className="h-2 rounded-full" /></View></View>; }
